variables:
  SampleName: Hybrid-Shadows
  CMakeConfig: -G "Visual Studio 16 2019" -A x64
  CaudronMediaUrl: http://isvgit.amd.com/raguaviv/cauldron-media/-/archive/master/cauldron-media-master.zip
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - deploy

build_dx12:
  tags:
  - windows
  - amd64
  stage: build
  artifacts:
    paths:
    - bin/
  script:
  - 'cmake -S . -B build/DX12 -DGFX_API=DX12 %CMakeConfig%'
  - 'cmake --build build/DX12 --config Release'

package_sample:
  tags:
  - windows
  - amd64
  stage: deploy
  dependencies:
    - build_dx12
  script:
  - move NOTICES.txt %SampleName%
  artifacts:
      name: "%SampleName%-%CI_COMMIT_TAG%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHORT_SHA%"
      paths:
      - "bin/"
      - "NOTICES.txt"
      - "media/cauldron-media/"
      - "readme.md"
      - "screenshot.png"
